
import React from 'react';
import { Landmark, ArrowLeft, ShieldAlert } from 'lucide-react';
import { Link } from 'react-router-dom';
import { PageTransition } from '../../../app/layout/PageTransition';
import { SopSection } from '../components/SopSection';

export const FinanceSopPage: React.FC = () => {
  return (
    <PageTransition>
      <div className="max-w-[1000px] mx-auto pb-20">
        <Link to="/training" className="inline-flex items-center gap-2 text-[10px] font-black uppercase tracking-widest text-slate-400 hover:text-indigo-600 mb-8 transition-colors">
          <ArrowLeft size={14} /> Back to Hub
        </Link>

        <div className="mb-12">
          <h1 className="text-3xl font-black text-slate-900 flex items-center gap-3">
            <Landmark className="text-amber-500" /> Finance & Reconciliation SOP
          </h1>
          <p className="text-slate-500 mt-2 font-medium">Audit-safe handling of invoices, taxes, and settlements.</p>
        </div>

        <div className="grid grid-cols-1 md:grid-cols-2 gap-8">
          <SopSection 
            title="Invoice & GST Compliance"
            type="checklist"
            items={[
              { text: "Verify Corporate GSTIN during reservation update" },
              { text: "Issue Tax Invoices only after check-out is complete" },
              { text: "Never edit tax breakup values manually (system-locked)" },
              { text: "Export GSTR-1 reports on the 1st of every month" }
            ]}
          />

          <SopSection 
            title="Settlement Reconciliation"
            type="bullet"
            items={[
              { text: "Match Razorpay settlement IDs with bank credits" },
              { text: "Track OTA commissions (15-20%) on every settlement" },
              { text: "Audit 'Pending Payouts' older than 7 business days" }
            ]}
          />

          <SopSection 
            title="Financial Governance"
            type="caution"
            items={[
              { text: "Do not process refunds without verifying original payment ID" },
              { text: "Do not issue multiple invoices for the same booking ID" },
              { text: "Ensure cash-in-hand matches 'Front Desk Cash' report daily" }
            ]}
          />

          <SopSection 
            title="Internal Audit Do's"
            type="success"
            items={[
              { text: "Run the 'Revenue by Source' report weekly" },
              { text: "Compare PMS revenue with Gateway portal totals" },
              { text: "Verify HSN codes (9963) for accommodation services" }
            ]}
          />
        </div>

        <div className="mt-12 bg-rose-50 border border-rose-100 rounded-[32px] p-8 flex items-start gap-6">
          <div className="p-4 bg-white rounded-2xl shadow-sm text-rose-500 shrink-0">
             <ShieldAlert size={28} />
          </div>
          <div>
            <h4 className="text-lg font-black text-rose-900 mb-1">Audit Compliance Note</h4>
            <p className="text-sm text-rose-700 leading-relaxed font-medium">
              Invoices generated by LuxeStay are legally binding audit documents. Once issued, do not cancel them unless there is a material error in guest information. For revenue adjustments, use the 'Adjustment' module rather than editing historical records.
            </p>
          </div>
        </div>
      </div>
    </PageTransition>
  );
};
